swagger: '2.0'
info:
  title: API de tarefas
  description: 'API para adição de tarefas'
  version: '1.0.0'

paths:
  /tarefa/nova:
    post:
      summary: Adiciona uma nova tarefa
      description: Adiciona uma nova tarefa à lista de tarefas
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: body
          description: Objeto JSON com o título e a descrição da tarefa
          required: true
          schema:
            type: object
            properties:
              titulo:
                type: string
                example: 'Comprar pão'
              descricao:
                type: string
                example: 'Comprar pão na padaria da esquina'
      responses:
        200:
          description: Tarefa adicionada com sucesso
          schema:
            type: object
            properties:
              titulo:
                type: string
                example: 'Comprar pão'
              descricao:
                type: string
                example: 'Comprar pão na padaria da esquina'
